version: '3'

vars:
  PYTHON: .venv/bin/python
  PIP: .venv/bin/pip
  ARCHIVE_CSV: dataset/saveecobot-cities-pm25-and-aqi-pm25.csv
  RAW_DIR: data/raw
  PROCESSED_DIR: data/processed
  FIGURES_DIR: outputs/figures
  QA_DIR: outputs/qa

includes: {}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup:
    desc: Create virtualenv and install dependencies
    status:
      - test -d .venv
    cmds:
      - test -d .venv || python -m venv .venv
      - '{{.PIP}} install --upgrade pip'
      - '{{.PIP}} install -r requirements.txt'

  ingest:
    desc: Ingest hourly CSVs (per-year + combined archive) into parquet
    deps: [setup]
    status:
      - test -f {{.RAW_DIR}}/city_hourly_2025.parquet
    cmds:
      - '{{.PYTHON}} -m src.pipeline.run ingest --hourly-pattern "dataset/saveecobot_cities_pm25_and_aqi_pm25_*.csv" --cities-metadata dataset/saveecobot_cities.csv --raw-dir {{.RAW_DIR}} --archive-csv {{.ARCHIVE_CSV}}'

  aggregate:
    desc: Aggregate hourly data to daily/city/regional tables with eligibility filters
    deps: [ingest]
    status:
      - test -f {{.PROCESSED_DIR}}/city_daily_pm25.parquet
    cmds:
      - '{{.PYTHON}} -m src.pipeline.run aggregate --raw-dir {{.RAW_DIR}} --processed-dir {{.PROCESSED_DIR}} --cities-metadata dataset/saveecobot_cities.csv --admin-boundaries dataset/geo/ukraine_adm_boundaries.geojson --timezone Europe/Kyiv --wartime-start 2022-02-24 --pm25-guideline 15'

  qa:
    desc: Generate QA summaries for eligible city set
    deps: [aggregate]
    status:
      - test -f {{.QA_DIR}}/qa_summary.json
    cmds:
      - '{{.PYTHON}} -m src.pipeline.run qa --processed-dir {{.PROCESSED_DIR}} --qa-dir {{.QA_DIR}} --pm25-guideline 15'

  figures:
    desc: Render the full suite of publication-ready figures
    deps: [aggregate]
    status:
      - test -f {{.FIGURES_DIR}}/08_choropleth.png
    cmds:
      - '{{.PYTHON}} -m src.visualization.run all --processed-dir {{.PROCESSED_DIR}} --figures-dir {{.FIGURES_DIR}}'

  pipeline:
    desc: Run ingest, aggregate, and QA stages sequentially
    cmds:
      - task: qa

  full:
    desc: Run the complete workflow (pipeline + figures)
    cmds:
      - task: pipeline
      - task: figures

  clean:
    desc: Remove processed artefacts and outputs (keeps raw CSVs)
    cmds:
      - rm -rf {{.RAW_DIR}} {{.PROCESSED_DIR}} {{.FIGURES_DIR}} {{.QA_DIR}}
      - mkdir -p {{.RAW_DIR}} {{.PROCESSED_DIR}} {{.FIGURES_DIR}} {{.QA_DIR}}
